### ISSUE TITLE
HBase counterparts to Cloud Bigtable's RowFilter API

### ISSUE THREAD

**Issue by sduskis** [googleapis/java-bigtable-hbase#1510]
Create HBase filters under the CBT package that look more like CBT's [RowFilter](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-protos/src/main/proto/google/bigtable/v2/data.proto#L211).

**Comment by igorbernstein2** [comment]
I dont think we can/should do this. The bigtable models should be treated as an implementation detail
