### ISSUE TITLE
Be able to run tests in non-shaded artifacts.

### ISSUE THREAD

**Issue by sduskis** [googleapis/java-bigtable-hbase#1630]
Most files are the same, so we should avoid code duplication.

Also, it would be quite nice if we could test against unshaded bigtable-hbase instead of the hadoop artifact; that would allow us to reduce build time by a non-trivial amount.

**Comment by igorbernstein2** [comment]
Historical note:
The main issue with testing against the nonshaded bigtable-hbase is that the nonshaded version of our client depends on hbase-shaded-client, which conflicts with the hbase-client in the hbase minicluster. My original plan was to isolate the hbase minicluster from the main classpath by moving it into a maven plugin, however I ran into dependency conflicts between maven & hbase.
