### ISSUE TITLE
AbstractRetryingOperation should ensure that only a single retry is in progress

### ISSUE THREAD

**Issue by sduskis** [googleapis/java-bigtable-hbase#1717]

**Comment by rahulKQL** [comment]
@igorbernstein2, @sduskis, @kolea2  I was going through `AbstractRetryingOperation`. I thought of these basic approaches for this. Please let me know your view on the same.

One approach would be to maintain an `AtomicBoolean` which will be set in [`AbstractRetryingOperation#performRetry()`](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AbstractRetryingOperation.java#L238-L244) and gets reset in the callback of the result of `retryExecutorService.schedule(..)`.
 
Another approach would be to keep an atomic counter with a default value of  1(which represent the first attempt); Then increment this in [`AbstractRetryingOperation#getNextBackOff()`](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AbstractRetryingOperation.java#L272-L303) once RPC is resolved,  it'd be decremented in [`AbstractRetryingOperation#onClose(..)`](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AbstractRetryingOperation.java#L161-L176).

**Comment by igorbernstein2** [comment]
Unless this is fixing a specific bug in the client, I would like to freeze work on the -core client and start refocusing efforts on swapping it out with gcj

**Comment by rahulKQL** [comment]
Sure, I was digging through some old issues and thought of approach. Will now focus on that then.
