### ISSUE TITLE
Suggested README updates & cleanups

### ISSUE THREAD

**Issue by mbrukman** [googleapis/java-bigtable-hbase#1949]
The project's top-level README still uses 1.5.0 as the version in library config samples, when 1.6.0 is the latest version.

There are no examples of using `hbase-2.x` artifacts.

Artifact names should be written in code font as they literally are `hbase-1.x` or `hbase-2.x`; when not written in code font, they appear to be imprecise and customers might assume they need to substitute an actual minor version number for the `x`. Using code formatting will clarify this.

**Comment by meredithslota** [comment]
It looks like this was addressed in https://github.com/googleapis/java-bigtable-hbase/pull/2167 — closing. Please reopen or file a new issue if this is not satisfactorily fixed.
