### ISSUE TITLE
URL and SCM section in bigtable-client-core pom.xml

### ISSUE THREAD

**Issue by suztomo** [googleapis/java-bigtable-hbase#2278]
Would you add URL and SCM section in pom.xml files in this repository?

Background:
While checking https://issues.apache.org/jira/browse/BEAM-8627, I wanted to see the history of BigtableTableName class in bigtable-client-core. I had to search for the Git repository for the artifact [bigtable-client-core](https://search.maven.org/artifact/com.google.cloud.bigtable/bigtable-client-core/1.12.1/jar) and spent 5 minutes to find this repository "java-bigtable-hbase".

**Comment by rahulKQL** [comment]
Thanks for pointing it out, The repository information is now updated in pom.xml.

**Comment by suztomo** [comment]
Thank you.
