### ISSUE TITLE
Unable To Connect To BigTable - com.google.api.client.http.HttpResponseException: 502 cannotconnect

### ISSUE THREAD

**Issue by nitinware** [googleapis/java-bigtable-hbase#2291]
I am not able to connect to GCP BigTable instance using HBASE Client ./quickstart.sh, seeing below error : 

```
Dec 02, 2019 9:33:45 AM com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
WARNING: Failed to detect whether we are running on Google Compute Engine.
com.google.api.client.http.HttpResponseException: 502 cannotconnect
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--
  Message.TemplateName: cannotconnect
  Message.Language: 
-->
<html>
<!-- head -->
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
  <title>McAfee Web Gateway - Notification - </title>
  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
  <link rel="stylesheet" type="text/css" href="/mwg-internal/de5fs23hu73ds/files/HomeDepot/stylesheet.css" />
</head>
<!-- /head -->
```

**Comment by rahulKQL** [comment]
I believe you are trying to run [quickstart](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/quickstart) project.  
Are you trying to run this example on your local machine or compute engine?  If compute engine then Have you enabled both the **Cloud Bigtable API** and the **Cloud Bigtable Admin API** for your compute engine instance?

**Comment by nitinware** [comment]
@rahulKQL - Thanks for the reply, Yes I am running quickstart project locally on my mac, not on compute engine, would like to know a fix for running this locally on Mac.

**Comment by rahulKQL** [comment]
Please make sure the `GOOGLE_APPLICATION_CREDENTIALS` is pointing towards your google cloud credentials json file. If not using JSON file. If not using json file then please have a look at [this](https://googleapis.dev/python/google-api-core/latest/auth.html#overview) documentation for local authentication.
