### ISSUE TITLE
Add kokoro job for sequencefile importer

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable-hbase#2367]
To prevent #2366 from re-occurring, we need to have a kokoro test for the sequencefileIntegrationTest profile

something like:

mvn verify \
  -pl bigtable-dataflow-parent/bigtable-beam-import \
  -Dgoogle.bigtable.instance.id="int-tst" \
  -Dgoogle.bigtable.project.id="PROJECT_ID" \
  -Dgoogle.dataflow.stagingLocation="gs://SOME_GCS_PATH_TO_USE_FOR_TEMP_FILES" \
  -Dcloud.test.data.folder="gs://SOME_GCS_PATH_TO_USER_FOR_TEMP_DATA_FILES/" \
  -PsequencefileIntegrationTest

**Comment by dmitry-fa** [comment]
#2623 covers this request, so I'm closing it
