### ISSUE TITLE
release scheme issues

### ISSUE THREAD

**Issue by czka** [googleapis/java-bigtable-hbase#2377]
What is the relation between [1] and [2]?

The last release properly announced on [2] is 1.12.0. On [1], there are also jars for 1.12.1 and 1.13.0 though.

How do I understand it that 1.12.1 and 1.13.0 don't have any release notes on [2]? They may have a considerable amount of changes compared to 1.12.0, as they implement SDK version 2.14.0 and 2.15.0, respectively, whereas 1.12.0 is on SDK 2.11.0...

We have some tooling using the shaded jar 1.12.0 from [1]. Should I consider versions 1.12.1 and 1.13.0 sort of "unofficial", "not recommended" or something?

Google is going to obsolete SDK 2.11.0 in March this year, as per [3]. So I guess I should move to SDK 2.14.0/2.15.0, meaning I should start using the shaded jars 1.12.1/1.13.0, but the unclear status of those versions on [2] is confusing and problematic.

I would appreciate it if you could answer my questions and clarify the status by publishing release notes for 1.12.1 and 1.13.0 on [2].

[1] https://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-beam-import/
[2] https://github.com/googleapis/java-bigtable-hbase/releases
[3] https://cloud.google.com/dataflow/docs/support/sdk-version-support-status

**Comment by igorbernstein2** [comment]
Hi @czka,

I apologize for the lack of release notes, this was an omission on my part. I will publish them soon, but for now the quick summary is that there should be no breaking changes to the beam connector between those versions. Those releases primarily focused on updating dependencies, annotating the public surface and CI changes. The only technically breaking change is related to changes an internal abstraction layer that was not marked as private.

We will work towards upgrading the beam version in the next release to avoid the need for shading.

**Comment by igorbernstein2** [comment]
I've backfilled the release notes and we've updated beam. Sorry about the inconvenience

**Comment by czka** [comment]
Thanks @igorbernstein2!
