### ISSUE TITLE
RowAdapter implementation doesn't skip RowCell with labels

### ISSUE THREAD

**Issue by rahulKQL** [googleapis/java-bigtable-hbase#2384]
This is related to [RowAdapter#adaptResponse](https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/RowAdapter.java#L42-L69).

If a `RowCell` with labels is present in the `Row` then the current implementation of `RowAdapter` is not filtering them out. The [JUnit test case](https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/adapters/read/TestRowAdapter.java#L111-L140) for this scenario was working because of `TreeSet` not because of skipping RowCell with labels.

**Comment by igorbernstein2** [comment]
I think this is obsolete now that we pushed this logic into the whilescanadapter
