### ISSUE TITLE
Extract out trace management from ResultScanners

### ISSUE THREAD

**Issue by rahulKQL** [googleapis/java-bigtable-hbase#2458]
Related to [#2444](https://github.com/googleapis/java-bigtable-hbase/pull/2444#discussion_r397181648) 

While transitioning the `BigtableWhileMatchResultScannerAdapter` with new DataClientWrappers the `span`s are now are left open, It needs to be closed/ends explicitly when the read stream ends.

**Comment by igorbernstein2** [comment]
I dont think that scans should have spans attached as there is no way to ensure that they are ever completed. Instead the underlying ReadRowsOperation should have a span since we have a means to ensure a bounded lifetime

**Comment by igorbernstein2** [comment]
This will be covered in the veneer metrics integration
