### ISSUE TITLE
SingleColumnValueExcludeFilterAdapter seems to be incorrectly implemented

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable-hbase#2479]
It seems like an unintentional change in:

https://github.com/googleapis/java-bigtable-hbase/commit/9a2ddf040bc192b1e9d3adf1c7af9b4cb2362393#diff-7a60b09f1dcbaeaf614760677486830cL60

changed the subfilter from a chain to an interleave.

@rahulKQL can verify that this was in fact a mistake?
@kolea2 if this turned out to be a mistake we will have to create a bugfix branch and release a point release

**Comment by rahulKQL** [comment]
It seems the implementation is valid. In the original implementation also the subFilter is interleaved. 
I also ran a test case against both the implementation just to verify my doubt it worked fine. Could you please have one more look.

**Comment by igorbernstein2** [comment]
My apologies, this was reported by a customer and I misread the implementation
