### ISSUE TITLE
HBase incompatibilty checkAndMutate.ifEquals(new byte[0]) fails on missing value

### ISSUE THREAD

**Issue by clehene** [googleapis/java-bigtable-hbase#2510]
#### Environment details

1. Specify the API at the beginning of the title. General, Core, and Other are also allowed as types
2. OS type and version: osx / linux
3. Java version: 8
4. Version(s): hbase-2.2.3 , bigtable-1.14

#### Steps to reproduce

check and mutate on a new row / f / q while testing for equality with empty byte array works on HBase but fails on BigTable. 

#### Code example

```java
    byte[] row = Bytes.toBytes("test" + random.nextInt());
    Put put = new Put(row);
    put.addColumn(UserDao.META, UserDao.USER_INFO, Bytes.toBytes("value"));
    boolean success = table.checkAndMutate(row, UserDao.META)
        .ifEquals(new byte[0]).qualifier(USER_INFO)
        .thenPut(put);
```

#### External references such as API reference guides

I couldn't find anything related to empty byte array

#### Any additional information below

This seems to be in the same area as https://github.com/googleapis/java-bigtable-hbase/issues/1704#issuecomment-371278836

**Comment by dmitry-fa** [comment]
@clehene

Thanks for submitting this issue.
I'm not able to reproduce the bug: `checkAndMutate()` works as expected on missing value.
In the description you didn't provide information how do you obtain the table instance.
Maybe we are talking about different BigTables.

I use the following maven dependencies:

```
        <dependency>
            <groupId>org.apache.hbase</groupId>
            <artifactId>hbase-client</artifactId>
            <version>2.2.3</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud.bigtable</groupId>
            <artifactId>bigtable-hbase-2.x</artifactId>
            <version>1.14.0</version>
        </dependency>
```
And the following code to reproduce the bug:
```
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.hbase.TableName;
import org.apache.hadoop.hbase.client.AdvancedScanResultConsumer;
import org.apache.hadoop.hbase.client.AsyncTable;
import org.apache.hadoop.hbase.client.BigtableAsyncConnection;
import org.apache.hadoop.hbase.client.Put;
import org.apache.hadoop.hbase.util.Bytes;
import java.util.Random;

public class CheckAndMutate {
  static String projectId = "the-project-id";
  static String instanceId = "the-instance-id";
  static String tableId = "the-table";
  static Random random = new Random();

  public static void main(String... args) throws Exception {
    Configuration configuration = new Configuration();
    configuration.set("google.bigtable.project.id", projectId);
    configuration.set("google.bigtable.instance.id", instanceId);
    BigtableAsyncConnection connection = new BigtableAsyncConnection(configuration);
    TableName tableName = TableName.valueOf(tableId);

    AsyncTable<AdvancedScanResultConsumer> table = connection.getTableBuilder(tableName).build();
    System.out.println("Table class: " + table.getClass().getCanonicalName());


    byte[] row = Bytes.toBytes("test" + random.nextInt());
    byte[] family = Bytes.toBytes("familiy");
    byte[] q = Bytes.toBytes("qualifier");


    Put put = new Put(row);
    put.addColumn(family, q, Bytes.toBytes("value"));

    table.checkAndMutate(row, family).qualifier(q).ifEquals(new byte[0]).thenPut(put)
        .thenAccept(success -> {
          System.out.println("success: " + success);
        }).get();
  }

}
```

To continue investigation I need more details from you.

Thanks

**Comment by igorbernstein2** [comment]
@dmitry-fa would you mind converting your example into an integration test in 
https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestCheckAndMutate.java

**Comment by dmitry-fa** [comment]
@igorbernstein2 yes, sure. But this particular test is probably not very interesting. I can look at the existing test cases for that area, probably I can suggest something better.

**Comment by kolea2** [comment]
Hi @clehene, do you have any additional details you can provide @dmitry-fa to help investigate? Thank you!

**Comment by clehene** [comment]
@kolea2 I have failing unit test that we keep around for this.

Not 

```
  @Test
  @DisplayName("HBase/BT incompatibility")
    // https://github.com/googleapis/java-bigtable-hbase/issues/2510
    // This works on HBase but fails on BigTable
  void WATER1127() throws IOException {
    Table table = hBaseUtils.getTable(config.getString(STORAGE_USERS_TABLE));
    byte[] row = Bytes.toBytes("test" + random.nextInt());
    Put put = new Put(row);
    put.addColumn(UserDao.META, UserDao.USER_INFO, Bytes.toBytes("value"));
    boolean success = table.checkAndMutate(row, UserDao.META)
        .ifEquals(new byte[0]).qualifier(USER_INFO)
        .thenPut(put);
    assertThat(success).isTrue();
  }

``` 
The connection is with `com.google.cloud.bigtable.hbase2_x.BigtableConnection`

```
connection = ConnectionFactory.createConnection(getConfiguration());
```

The connection config 

```
  public Configuration getConfiguration() {
    Configuration hbaseConfig = HBaseConfiguration.create();

    if (config.hasPath(HBASE_CONN_IMPL) && config.getString(HBASE_CONN_IMPL).contains("Bigtable")) {
      String hbConnImpl = config.getString(HBASE_CONN_IMPL);
      logger.atInfo().log("HBase connection impl %s ", hbConnImpl);

      String btProjectId = config.getString(GCP_PROJECT);
      String btInstanceId = config.getString(BT_INSTANCE_ID);
      Configuration config = BigtableConfiguration.configure(btProjectId, btInstanceId);
      //config.set(BigtableOptionsFactory.APP_PROFILE_ID_KEY, APP_PROFILE_ID);

      hbaseConfig.set(BT_PROJECT_ID, btProjectId);
      hbaseConfig.set(BT_INSTANCE_ID, btInstanceId);
      hbaseConfig.set(HBASE_CONN_IMPL, hbConnImpl);
      return config;
      //String btEmulatorHost = config.getString(BT_EMULATOR_HOST);
      //if (btEmulatorHost.length() > 0) {
      //  hbaseConfig.set(BT_EMULATOR_HOST, btEmulatorHost);
     // }
    } else {
      String zkQuorum = config.getString(ZK_QUORUM);
      hbaseConfig.set(ZK_QUORUM, zkQuorum);
    }

    /*
     * hbase.client.operation.timeout valid for each client call. When an RPC call fails for
     * instance for a timeout due to hbase.rpc.timeout it will be retried until
     * hbase.client.operation.timeout is reached
     */
    hbaseConfig.setInt(HConstants.HBASE_CLIENT_OPERATION_TIMEOUT, 5000);
    /*
     * same as hbase.client.operation.timeout but for system tables
     */
    hbaseConfig.setInt(HConstants.HBASE_CLIENT_META_OPERATION_TIMEOUT, 1000);
    hbaseConfig.setInt(HConstants.HBASE_CLIENT_SCANNER_TIMEOUT_PERIOD, 10000);
    hbaseConfig.setInt(HConstants.HBASE_RPC_TIMEOUT_KEY, 2000);
    hbaseConfig.setInt(HConstants.HBASE_RPC_READ_TIMEOUT_KEY, 2000);
    hbaseConfig.setInt(HConstants.HBASE_RPC_WRITE_TIMEOUT_KEY, 2000);
    hbaseConfig.setInt(HConstants.HBASE_CLIENT_RETRIES_NUMBER, 2);
    hbaseConfig.setInt(ReadOnlyZKClient.RECOVERY_RETRY, 2);
    return hbaseConfig;
  }

```

**Comment by dmitry-fa** [comment]
Hi @clehene, thanks for extra details. I updated the example to use `com.google.cloud.bigtable.hbase2_x.BigtableConnection`, but the result is the same: result is `false`.

Are you sure that your test is correct:
```

    byte[] row = Bytes.toBytes("test" + random.nextInt());
    Put put = new Put(row);
    put.addColumn(UserDao.META, UserDao.USER_INFO, Bytes.toBytes("value"));
    boolean success = table.checkAndMutate(row, UserDao.META)
        .ifEquals(new byte[0]).qualifier(USER_INFO)
        .thenPut(put);
    assertThat(success).isTrue();

```
The test expects that the row is successfully mutated. I would expect that `success` is false.

**Comment by clehene** [comment]
@dmitry-fa glad to discuss whether it *should* be `true` or `false`. What I'm seeing is that HBase and BigTable return opposing values. 

Now for what HBase actually *does*: 


I haven't been in touch with the HBase code base in the last few years, but I believe this is the actual piece that we care about  from `HRegion.checkAndMutate` (https://github.com/apache/hbase/blob/branch-2/hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java#L4760)

```java
          boolean valueIsNull = comparator.getValue() == null || comparator.getValue().length == 0;
          // this-----------------------------------------------------------------------------^^^^^
          if (result.isEmpty() && valueIsNull) {
            matches = true;
          //  ------------------------ THIS ----------------------------
          } else if (result.size() > 0 && result.get(0).getValueLength() == 0 && valueIsNull) {
          //  ------------------------ THIS -------------------------^^^^^^^^^ ---
            matches = true;
            cellTs = result.get(0).getTimestamp();
          } else if (result.size() == 1 && !valueIsNull) {
            Cell kv = result.get(0);
            cellTs = kv.getTimestamp();
            int compareResult = PrivateCellUtil.compareValue(kv, comparator);
            matches = matches(op, compareResult);
          }
```

It can't be null however because there's a client precondition 
https://github.com/apache/hbase/blob/branch-2/hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java#L1290

Here's the unit test the 'codifies' the rule

https://github.com/apache/hbase/blob/branch-2/hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java#L1795
```java
    boolean res = region.checkAndMutate(row1, fam1, qf1, CompareOperator.EQUAL,
        new BinaryComparator(emptyVal), put);
    assertTrue(res);
```

**Comment by clehene** [comment]
Hi,

Given that this violates test and set semantics it should be P1. 
Our entire code base is littered with if / else statements to work around this and we're still finding live issues because of it. 

To get a sense of how bad this is, consider a simple protobuf object. When a message field x is not set and you try to `getX().toByteArray()` it will return an empty byte array. If you try to do an `ifEquals` mutation, it will fail.

**Comment by dmitry-fa** [comment]
Hi @clehene, thanks for the new arguments.

> @dmitry-fa glad to discuss whether it should be true or false. What I'm seeing is that HBase and BigTable return opposing values

If I understand your position right, you state that "something does not exist or not set" must be treated as "something is equal to zero bytes", because HBase does that.
I think it's not a subject for discussion, it must be specified. Unfortunately, I haven't found any document that could clarify that behavior, but I will keep searching.

> To get a sense of how bad this is, consider a simple protobuf object. When a message field x is not set and you try to getX().toByteArray() it will return an empty byte array. If you try to do an ifEquals mutation, it will fail.

I would expect fail in such situation. One can use the following code instead:
```
    boolean success = table.checkAndMutate(row, family)
        .ifNotExists().qualifier(q)
        .thenPut(put);
```
Otherwise, I don't know how to distinguish rows where some values have been set to "" from rows where that values haven't been set yet.

**Comment by clehene** [comment]
@dmitry-fa 

We're using that workaround. Our code is littered with these:

```
    if (maybeX.isPresent() && maybeX.get().hasInfo()) {
      // ifEquals only works for existing values with BigTable
      // See https://github.com/googleapis/java-bigtable-hbase/issues/2510
      // See https://..
      // See https://..
      mutateBuilder.ifEquals(currentInfo.toByteArray());
    } else {
      mutateBuilder.ifNotExists();
    }
```

This is breaking core transactional semantics, yielding unexpected behavior if it's expected behavior it should be here
https://cloud.google.com/bigtable/docs/hbase-differences
And also this https://github.com/googleapis/java-bigtable-hbase/issues/2672

**Comment by kolea2** [comment]
Thank you @clehene for all of the details here - this is super helpful to understand the context. It sounds like we can either 1. try to update the behavior to match HBase or 2. document it as a known difference. I'll keep this thread updated once we determine what the best solution here is.
