### ISSUE TITLE
Add CI mechanism to check a commit messages

### ISSUE THREAD

**Issue by irvifa** [googleapis/java-bigtable-hbase#2561]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
I find that it will be easier to read the commit history if the commit have a type, description, and summary.

**Describe the solution you'd like**
This can be solved by using commit conventions, e.g: https://www.conventionalcommits.org/en/v1.0.0/ probably using Conventional Commit Lint GCF.

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Additional context**
Any other context or screenshots about the feature request.

**Comment by meredithslota** [comment]
Other repos (e.g. https://github.com/googleapis/java-bigtable) use a bot that checks for conventional commits — I wonder if we should add that here? It's here: https://github.com/googleapis/repo-automation-bots/tree/main/packages/conventional-commit-lint Thoughts, @kolea2?

**Comment by kolea2** [comment]
Conventional commit checking has been added to PRs. Thanks!
