### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by xavier-rasschaert-privitar** [googleapis/java-bigtable-hbase#2573]
Our product integrates with GCP and we depend on the maven dependency com.google.cloud.bigtable:bigtable-hbase-1.x-shaded to integrate with Bigtable. We noticed an issue when we are calling getTableRegions() in AbstractBigtableAdmin.java, which we require for an important production feature that we provide to our customers. The issue is fixed in https://github.com/googleapis/java-bigtable-hbase/pull/2447 on the 23rd of March. Unfortunately we are unable to find a release which contains that fix. Is there an upcoming release planned for https://github.com/googleapis/java-bigtable-hbase that would contain this fix?

**Comment by kolea2** [comment]
Thanks! I'm looking into it.

**Comment by kolea2** [comment]
Thanks for your patience! 1.15.0 has been released with this fix.
