### ISSUE TITLE
Looking for a thread-safe batch read API

### ISSUE THREAD

**Issue by gtbai** [googleapis/java-bigtable-hbase#2624]
Hi team,

I am looking for a thread-safe batch read API for Bigtable. I saw a candidate gRPC API [com.google.cloud.bigtable.grpc.BigtableDataClient#readFlatRowsAsync](https://github.com/googleapis/java-bigtable-hbase/blob/5a063bcbeab20f435f9a469c65966feb436a8820/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableDataClient.java#L183) implemented at [com.google.cloud.bigtable.grpc.BigtableDataGrpcClient#readFlatRowsAsync](https://github.com/googleapis/java-bigtable-hbase/blob/5a063bcbeab20f435f9a469c65966feb436a8820/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableDataGrpcClient.java#L366), which under the hood makes use of some streaming API. Is the underlying streaming API thread-safe?

**Comment by igorbernstein2** [comment]
Yes, readFlatRowsAsync is threadsafe. Sorry for the late reply
