### ISSUE TITLE
Is bigtable-hbase-beam still experimental?

### ISSUE THREAD

**Issue by udim** [googleapis/java-bigtable-hbase#2899]
I've just looked at the README.md and it hasn't been updated since the original PR.
Is the code stable enough to come out of experimental?

https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-dataflow-parent/bigtable-hbase-beam/README.md

**Comment by igorbernstein2** [comment]
hi,

We have a number of customers using it in production. The primary reason its still marked as experimental is that I would to eventually merge it with beam's HBaseIO

**Comment by udim** [comment]
Got it, thanks
