### ISSUE TITLE
BigtableSession leak at #2658 is not fixed yet

### ISSUE THREAD

**Issue by baeminbo** [googleapis/java-bigtable-hbase#2913]
The `BigtableSession` leak issue #2658  is not fixed yet because #2782 was reverted #2873.

This issue causes Dataflow pipeline with `CloudBigtableIO` to log error messages.
```
"*~*~*~ Channel ManagedChannelImpl{logId=43, target=bigtableadmin.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true." 
```

![bigtable_session_error](https://user-images.githubusercontent.com/49642083/113162320-082ac300-91f4-11eb-9ede-1d227862aef2.png)

**Comment by igorbernstein2** [comment]
Hi, thanks for pointing this out. I re-opened the original issue.
