### ISSUE TITLE
master branch is missing a couple of backup methods

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable-hbase#2939]
While porting the backups api to the master branch, I think we lost 2 methods on BigtableTableAdminGrpcClient:
- getBackupAsync
-  updateBackupAsync

Customers might be using those methods directly in bigtable-client-core so we cant remove them

**Comment by igorbernstein2** [comment]
Found one more:
public void deleteTableSnapshots(String tableNameRegex, String snapshotNameRegex)

in 1x:
https://github.com/googleapis/java-bigtable-hbase/blob/c945d7aab1433ed2d55bac3f216bc37c07f4227b/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L984-L987

in master:
https://github.com/googleapis/java-bigtable-hbase/blob/8c1eb6c5624357603a2e6f8ffcc277384390643c/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L959-L962

**Comment by igorbernstein2** [comment]
Also for getBackupClusterName, in 1x, the error message guides endusers to set a config value, but in master the guidance is missing:
https://github.com/googleapis/java-bigtable-hbase/blob/c945d7aab1433ed2d55bac3f216bc37c07f4227b/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L944-L947

**Comment by igorbernstein2** [comment]
One more missing method:

https://github.com/googleapis/java-bigtable-hbase/blob/c945d7aab1433ed2d55bac3f216bc37c07f4227b/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L899-L908

**Comment by kolea2** [comment]
> Found one more:
> public void deleteTableSnapshots(String tableNameRegex, String snapshotNameRegex)
> 
> in 1x:
> https://github.com/googleapis/java-bigtable-hbase/blob/c945d7aab1433ed2d55bac3f216bc37c07f4227b/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L984-L987
> 
> in master:
> https://github.com/googleapis/java-bigtable-hbase/blob/8c1eb6c5624357603a2e6f8ffcc277384390643c/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L959-L962

This delegates to an unsupported method, so I think this one is fine.

**Comment by kolea2** [comment]
> Also for getBackupClusterName, in 1x, the error message guides endusers to set a config value, but in master the guidance is missing:
> https://github.com/googleapis/java-bigtable-hbase/blob/c945d7aab1433ed2d55bac3f216bc37c07f4227b/bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java#L944-L947

The way cluster name is obtained differs between 1x and master. In master, we call `listClusters` and assert that the cluster size is 1. Is that sufficient?

**Comment by kolea2** [comment]
Fixed the missing `cloneSnapshot`.
