### ISSUE TITLE
Table#delete(List) should mutate the list in place and remove successful actions

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable-hbase#2998]
According to
https://hbase.apache.org/1.4/apidocs/org/apache/hadoop/hbase/client/Table.html#delete(java.util.List)

When an error happens, the list should get modified to only include failed deletes

**Comment by mutianf** [comment]
Released in https://github.com/googleapis/java-bigtable-hbase/releases/tag/v1.21.0
